<?php

/**
 * @file
 * Contains test_demo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function test_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom module.
    case 'help.page.custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('custom module for test_demo tasks') . '</p>';
      return $output;

    default:
  }
}


/*
*
* Implements hook_form_FORM-ID_alter
* This is to Add New field in Site information page
* By default, test_demo.settings siteapikey will be empty.
*/
function test_demo_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  $siteapikey = '';
  $siteapikey = \Drupal::config('test_demo.settings')->get('siteapikey');
  $form['site_information']['siteapikey'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => $siteapikey,
    '#placeholder' => t('No API Key yet'),
  );
  $form['actions']['submit']['#value'] = t('Update Configuration');
  //Submit handler to store siteapikey value into test_demo.setting
  $form['#submit'][] = 'test_demo_siteinformation_submit_handler';
}
//Submit handler to store siteapikey value into test_demo.setting
function test_demo_siteinformation_submit_handler(&$form, FormStateInterface $formState) {
  
  if( false == empty( $form['site_information']['siteapikey']['#value'] ) && $form['site_information']['siteapikey']['#value'] != \Drupal::config('test_demo.settings')->get('siteapikey') ) {

    \Drupal::configFactory()->getEditable('test_demo.settings')
      ->set('siteapikey', $form['site_information']['siteapikey']['#value'])
      ->save();
    drupal_set_message($form['site_information']['siteapikey']['#value'].' - Site API Key updated.');
  }
}
